### ISSUE TITLE
Daily Ops Week of 15/04/2024

### ISSUE THREAD

**Issue by tarunima** [tattle-made/DAU#97]

**Comment by dennyabrain** [comment]
Reply to Query 495

- I approved the two fact check articles
- Regenerated the response and saved it as the user response in database. This is now also visible in the portal. If you go to the media details page for query 495, the new generated user response is in place.
- You can also go to the message's delivery status page to see that it has been sent to the user using the notification api.
- In the delivery report it says "025 : SENT : SENT : 5148466418607268059-b17beabd-f8a2-4db7-913c-d2346eb6bbab"

Commands used : 
```elixir
alias DAU.UserMessage
import Ecto.Changeset
alias DAU.UserMessage.Outbox
alias DAU.Feed

common = Repo.get(Common, 495) 
template = Factory.process(common)
{:ok, text} = Factory.eval(template) 

Feed.add_user_response(495, text)

outbox |> cast(%{reply_type: "notification", text: text}, [:reply_type, :text]) |> Repo.update

outbox = Repo.get(Outbox, "b17beabd-f8a2-4db7-913c-d2346eb6bbab")
UserMessage.send_response(outbox)
```

**Comment by dennyabrain** [comment]
Reply to Query 457

Somehow this response had not been sent out. From what I could tell it was an oversight. All i did was click on the "approve response" button in the dashboard. and then initiate the send function through code.

```elixir
outbox = Repo.get(Outbox, "e07f8686-135a-4354-8b3c-91ebbc632a2e")
UserMessage.send_response(outbox)
```

**Comment by dennyabrain** [comment]
Reply to Query 473

**Background**
There was no matching template response for this user since the user's preferred language was hindi. Till we whitelist responses in hindi, we are defaulting to replying in English but that feature is not exposed in the portal. So we need to generate the template and set response using code.

```elixir
common = Repo.get(Common, 473)
meta = template.meta
new_meta = Map.put(meta, :template_name, "not_ai_generated_wo_ar_0fc_en")
new_template = Map.put(template, :meta, new_meta)
Factory.eval(new_template)
{:ok, text} = Factory.eval(new_template)

Feed.add_user_response(473, text)
common = Repo.get(Common, 473)
UserMessage.add_response_to_outbox(common) 
outbox = Repo.get(Outbox, "b246ffbc-d4bf-41b0-be8d-21b66db576bc")
UserMessage.send_response(outbox)
```

Result, all the tasks on the dashboard are done. After we hit send we havent received any delivery report from Gupshup. This means the message didn't get delivered to the user. We've raised a ticket with gupshup.

**Comment by aatmanvaidya** [comment]
**Issue** in Query 485 and 486
- When DAU tried to  to send out the user response for 'out of scope' < it didn't go the first time < it showed 'no matching template found' < tried a second time and it was sent
- same thing happened for  for 'Not AI generated' < didn't go the first time < went out when tried again.

**possible reason why this could be happening**
- upon refreshing the fields are all good, that means it must have been a momentary UI glitch
- doesn't affect the response being saved in the database or being sent to the user.

**Comment by dennyabrain** [comment]
Issue in query 498 and 499.

The secratariat mistaken approved the response for both the queries even when there was no matching template for it. These posts were given the label "manipulated", an assessment report was attached, 2,3 fact check articles were added and the secratariat approved those articles. There is no matching template for the scenario of "manipulated with assessment report and fact check articles" because it was decided that if a manipulated post has an assessment report, the fact check articles will be added to the article and not the user response.

Side Note : Given that this mistake of approving a response even when a matching template is not present makes me think that the "Approve Response" button should not be clickable when there is no matching template. This would make this even less error prone.

**Solution**
The first thing to do is to remove the approval for articles using the dashboard.

Then for both posts I regenerated the template response and stored in the database

For query 498
 
```elixir
common = Repo.get(Common, 498) 
template = Factory.process(common)
{:ok, text} = Factory.eval(template) 

Feed.add_user_response(498, text)

outbox = Repo.get(Outbox, "1e4e26af-c240-40d1-b9b6-3f8fda2d105a")
outbox |> cast(%{text: text}, [:text]) |> Repo.update
outbox = Repo.get(Outbox, "1e4e26af-c240-40d1-b9b6-3f8fda2d105a")
UserMessage.send_response(outbox)
```

**Comment by dennyabrain** [comment]
We eventually got the following delivery report for 473 
026 : READ : READ : 5148479698382426195-b246ffbc-d4bf-41b0-be8d-21b66db576bc

**Comment by dennyabrain** [comment]
Task : updated reply_type to notification for 508 and 513

508
```elixir
import Ecto.Changeset

outbox = Repo.get(Outbox, "8f6c7705-9ac0-4c2e-a4cd-401e77bcebcf")
outbox |> cast(%{reply_type: :notification}, [:reply_type]) |> Repo.update
```

513
```elixir
outbox = Repo.get(Outbox, "8d7eef96-ec14-4aa8-b61e-f26f328cce8a")
outbox |> cast(%{reply_type: :notification}, [:reply_type]) |> Repo.update
```

**Comment by dennyabrain** [comment]
Delivery Report for Query 532 says
```
 101 : FAILED : 24HR_TimeExceed : 5155587669424558126-d07ead1f-6249-4f84-85e4-41156ace7e4f
```

```elixir
Repo.get(Outbox, "d07ead1f-6249-4f84-85e4-41156ace7e4f") |> cast(%{reply_type: :notification}, [:reply_type]) |> Repo.update
outbox = Repo.get(Outbox, "d07ead1f-6249-4f84-85e4-41156ace7e4f")
UserMessage.send_response(outbox)
```

**Comment by tarunima** [comment]
closing this issue. Continuing here: https://github.com/tattle-made/DAU/issues/109
