### ISSUE TITLE
[16_W0] Able to filter unaddressed media

### ISSUE THREAD

**Issue by tarunima** [tattle-made/DAU#98]
### Is your feature request related to a problem? Please describe.

Being able to filter unaddressed media < media which we have not responded to (minus spam)-- 'taken up/not taken up'

### Describe the solution you would like

-

### Describe alternatives you've considered

-

### Addtional Context

-

**Comment by dennyabrain** [comment]
On the query page, we've added a new section to filter posts. Its titled "Taken up by". 


![Screenshot 2024-04-21 at 15-49-30 DAU · Deepfake Analysis Unit](https://github.com/tattle-made/DAU/assets/1415361/a044a276-5962-4fac-80ff-a3acb03a537c)

Choose "someone" to see posts that have been taken up by a user. Choose "no one" to see posts that haven't been taken up by anyone. These are posts that need help and could be a good starting point if you are trying to help out the secratariat.
choose "Show all" to see all posts without any filtering of the "taken up by" field.

I am not sure if the third option is the best solution to this. I considered making this a checkbox instead of a radio button. I also considered adding a "clear" icon that one could click to remove this filter. But they all felt like a new behaviour to learn for the secratariat and I felt could cause confusion, so I decided against it.

I think we are still at a point where we are trying to figure out what all filtering options are of use on the triaging page, so I am happy with doing these incremental additions to it. When this page gets too cluttered AND we have clarity on all the various ways in which the users want to slice and dice the data, we could do a UX exercise to revamping this page.
